### PR TITLE
Migrate database

### PR DESCRIPTION
**Pull request by wowKimsohyun17**
## Related Tickets:
- [#Ticket ID](https://edu-redmine.sun-asterisk.vn/issues/30253)

## WHAT this PR does?
migrate database

## Notes Impacted Areas:
- N/A.

## Attachments:
- N/A.

### CODE REVIEW

**Comment by wowKimsohyun17** [comment]
ready

**Comment by wowKimsohyun17** [comment]
ready

**Review by huyenttm-0901 — COMMENTED** [review]
thêm link ticket

**Comment by wowKimsohyun17** [comment]
ready

**Pull request merged**
